# Generated by Django 3.2 on 2023-06-11 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cvs', '0003_alter_personalinfomation_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalinfomation',
            name='user',
        ),
    ]
