# Generated by Django 3.2 on 2023-06-14 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvs', '0006_alter_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinfomation',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='personalinfomation',
            name='headline',
            field=models.CharField(default='example@mail.com', max_length=100, verbose_name='Headline'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personalinfomation',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone'),
        ),
    ]
