# Generated by Django 3.2 on 2023-06-17 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cvs', '0008_auto_20230617_0353'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experience',
            old_name='position',
            new_name='role',
        ),
    ]
