# Generated by Django 3.2 on 2023-06-17 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvs', '0010_experience_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalinfomation',
            name='bio',
        ),
        migrations.AddField(
            model_name='personalinfomation',
            name='summary',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Bio'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='description',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Describe your achievement'),
        ),
    ]
