# Generated by Django 3.2 on 2023-06-17 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cvs', '0011_auto_20230617_0434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='cv',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='education', to='cvs.cv'),
        ),
        migrations.AlterField(
            model_name='personalinfomation',
            name='cv',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='personal_info', to='cvs.cv'),
        ),
    ]
