# Generated by Django 3.2 on 2023-06-17 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cvs', '0012_auto_20230617_0808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='cv',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education', to='cvs.cv'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='cv',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='cvs.cv'),
        ),
    ]
