# Generated by Django 3.2 on 2023-06-28 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cvs', '0013_auto_20230617_0810'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personalinfomation',
            old_name='first_name',
            new_name='firsName',
        ),
        migrations.RenameField(
            model_name='personalinfomation',
            old_name='last_name',
            new_name='lastName',
        ),
    ]
