# Generated by Django 3.2 on 2023-06-28 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cvs', '0014_auto_20230628_0801'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personalinfomation',
            old_name='firsName',
            new_name='firstName',
        ),
    ]
