# Generated by Django 3.2 on 2023-07-03 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cvs', '0016_rename_lang_name_language_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='cv',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='cvs.cv'),
        ),
    ]
