# Generated by Django 3.2 on 2023-07-09 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvs', '0017_alter_skill_cv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
