# Generated by Django 3.2 on 2023-07-10 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvs', '0018_auto_20230709_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinfomation',
            name='dob',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date Of Birth'),
        ),
    ]
