# Generated by Django 3.2 on 2023-07-10 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvs', '0019_alter_personalinfomation_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='End'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Start'),
        ),
    ]
